LMBDA:
  default: 5000
  max: 30000
  min: 5000
  valstep: 10
MinDISP:
  default: -9
  max: 128
  min: -258
  valstep: 1
NumOfDisp:
  default: 96
  max: 256
  min: 16
  valstep: 16
PreFiltCap:
  default: 31
  max: 63
  min: 5
  valstep: 2
SIGMA:
  default: 3
  max: 5
  min: 0
  valstep: 0.1
SpcklRng:
  default: 5
  max: 40
  min: 0
  valstep: 1
SpklWinSze:
  default: 61
  max: 300
  min: 0
  valstep: 1
TxtrThrshld:
  default: 31
  max: 1000
  min: 0
  valstep: 1
UnicRatio:
  default: 4
  max: 100
  min: 1
  valstep: 1
