BlockSize:
  default: 1
  max: 51
  min: 1
  valstep: 2
Disp12MaxDiff:
  default: 7
  max: 10
  min: 0
  valstep: 1
LMBDA:
  default: 11810
  max: 30000
  min: 5000
  valstep: 10
MinDISP:
  default: -3
  max: 128
  min: -258
  valstep: 1
NumOfDisp:
  default: 96
  max: 256
  min: 16
  valstep: 16
SIGMA:
  default: 3
  max: 5
  min: 0
  valstep: 0.1
SpcklRng:
  default: 2
  max: 40
  min: 0
  valstep: 1
SpklWinSze:
  default: 200
  max: 300
  min: 0
  valstep: 1
UnicRatio:
  default: 4
  max: 100
  min: 1
  valstep: 1
