BlockSize:
  default: 5
  max: 51
  min: 1
  valstep: 2
Disp12MaxDiff:
  default: 0
  max: 10
  min: 0
  valstep: 1
LMBDA:
  default: 5000
  max: 30000
  min: 5000
  valstep: 10
MinDISP:
  default: 8
  max: 128
  min: -258
  valstep: 1
NumOfDisp:
  default: 64
  max: 256
  min: 16
  valstep: 16
SIGMA:
  default: 3
  max: 5
  min: 0
  valstep: 0.1
SpcklRng:
  default: 5
  max: 40
  min: 0
  valstep: 1
SpklWinSze:
  default: 61
  max: 300
  min: 0
  valstep: 1
UnicRatio:
  default: 4
  max: 100
  min: 1
  valstep: 1
